### PR TITLE
URDF importer locale warning

### PR DESCRIPTION
**Pull request by piotr-zyskowski-rai**
Since URDF parser uses locale information, it might incorrectly read files if the decimal delimiter is not compatible. This PR fixes this by forcing numeric locale to be `en_US.UTF-8` which is the most commonly used in the URDF files.

### CODE REVIEW

**Review by michalpelka — APPROVED** [review]

**Comment by adamdbrw** [comment]
This is not acceptable - this function affects the application:

"The modifications remain in effect and influences the execution of all locale-sensitive C library functions until the next call to setlocale"

If workaround is necessary (we could also use warnings / asserts for zero values with hints of the possible reason), set and restore just after parsing: you can query with https://en.cppreference.com/w/cpp/locale/locale.

**Review by adamdbrw — CHANGES_REQUESTED** [review]
Please add a warning instead on zero value

**Comment by adamdbrw** [comment]
@piotr-zyskowski-rai is it only applicable to cylinders? Or rather all primitive shapes (and both visual and colliders)

**Comment by piotr-zyskowski-rai** [comment]
> @piotr-zyskowski-rai is it only applicable to cylinders? Or rather all primitive shapes (and both visual and colliders)

@adamdbrw It most likely is. I tested it and it seems, however, that a zero-sized box or sphere of radius 0.0  does not cause Editor termination.

Locale incompatibility should actually cause way more problems, for example with the positions and rotations but there is no easy way to check that the value does not make sense for each case.

Locale incompatibility should cause problems with
- position, rotation - not much we can do here since all zeros rotation or translation are perfectly valid 
- scale - zero scale does not make any sense, might be worth notifying
- primitive sizes - the same
- inertial origin - perfectly fine with zeros
- inertial mass - zeros do not make any sense
- inertial inertia - all zeros do not make  sense, individual zeros do
- joint axis - all zeros do not make sense, individual zeros do
- color - all zeros make sense

And the question is whether we want to check guard all of the ones that we can, but still, have the URDF import fail. The whole robot will probably be messed up anyway. The cylinder is different because at the moment it causes violent Editor termination which is not nice and it would be nice to have a warning that is near the end of the log file with a hint of what might be the cause.

What we might do to tackle this issue overall, is to check the current locale settings before importing the URDF and print the warning if it is not `en_US` and only additionally guard the cylinder case, since it is "destructive".

What do you think?

**Comment by adamdbrw** [comment]
I agree - lets also submit an issue for cylinder to O3DE, it should not be behaving like this

**Review by adamdbrw — APPROVED** [review]

**Review by adamdbrw — APPROVED** [review]

**Pull request merged**
