### PR TITLE
Support for loading XACRO

### PR DESCRIPTION
**Pull request by michalpelka**
Signed-off-by: Michał Pełka <michalpelka@gmail.com>

### CODE REVIEW

**Review by pawelbudziszewski — COMMENTED** [review]
Works fine with xacro files.

Some minor comments:
- In the wizard descriptions, I'd change `URDF` to `URDF/XACRO`(or something like this)
- `This wizard allows you to build robot simulation [...]` text should be updated just like in the #297

**Comment by adamdbrw** [comment]
Looks good - just please add a task to handle parameters and some comments in the code - perhaps it would be best to extract xacro loading to a subroutine

**Review by pawelbudziszewski — COMMENTED** [review]
Works as expected, descriptions are fine. I have just a minor comment: 
Screenshot from 2022-12-09 11-22-45
In case of missing assets, would it be possible to write in the last column something like `Asset not found!`? The red color suggests, that there is a problem with such asset, but writing it explicitly would make it more obvious.

**Comment by michalpelka** [comment]
Was replaced with : https://github.com/o3de/o3de-extras/pull/90

**Pull request closed without merging**
